config/routes.rb
Blog::Application.routes.draw do
  devise_for :admins
  resources :posts do
    resources :comments
  end
  resources :welcome
  resources :albums do
    resources :photos
  end
  

   root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos, dependent: :destroy
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  
  has_attached_file :upload, :storage => :s3, :bucket => 'paisleythroughalens', :s3_credentials => { :access_key_id => 'AKIAJOBCA4KG6XNWDUVQ', :secret_access_key => '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'}, :styles => { :small => "300x300>", :large => "500x500>", :mobile => "1000x1000>" }
  validates_attachment_content_type :upload, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_attached_file :photo, :storage => :s3, :bucket => 'paisleythroughalens', :s3_credentials => { :access_key_id => 'AKIAJOBCA4KG6XNWDUVQ', :secret_access_key => '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'}, :styles => { :small => "300x300>", :large => "500x500>", :mobile => "1000x1000>" }
  validates :title, presence: true,
                    length: { minimum: 5 }
  validates_attachment_content_type :photo, :content_type => /\Aimage/
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end
  
  def new
    @album = Album.new
  end
  
  def create
    @album = Album.new(album_params)
    
    
    if @album.save
      redirect_to @album
    else
      render 'new'
    end
  end
  
  def show
    @album = Album.find(params[:id])
    
    @photos = @album.photos.all
  end
  
  def edit
    @album = Album.find(params[:id])
  end
  
  def update
    @album = Album.find(params[:id])
 
    if @album.update(album_params)
      redirect_to @album
    else
      render 'edit'
    end
  end
  
  def destroy
    @album = Album.find(params[:id])
    
    @album.destroy
    redirect_to albums_path
  end

  
  private
  
  def album_params
    params.require(:album).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper :all
  protect_from_forgery with: :exception
  before_filter :check_for_mobile

  # After sign in redirect to admin index page
  def after_sign_in_path_for(resource)
  root_path
  end

  def check_for_mobile
    session[:mobile_override] = params[:mobile] if params[:mobile]
    prepare_for_mobile if mobile_device?
  end

  def prepare_for_mobile
    prepend_view_path Rails.root + 'app' + 'views_mobile'
  end

  def mobile_device?
    if session[:mobile_override]
      session[:mobile_override] == "1"
    else
      # Season this regexp to taste. I prefer to treat iPad as non-mobile.
      (request.user_agent =~ /Mobile|webOS/)
    end
  end
  helper_method :mobile_device?


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    CommentMailer.comments_notification(@comment, @post).deliver
    redirect_to welcome_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @album = Album.find(params[:album_id])
    @photo = @album.photos.create(photo_params)
      
    respond_to do |format|
        format.js
    end
  end
  
  def destroy
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
    @photo.destroy
    redirect_to album_path(@album)
  end
  
  private
  
  def photo_params
    params.require(:photo).permit(:upload)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, except: [:show]
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
     @post = Post.new(params[:post].permit(:title, :text, :photo))
     
     if @post.save
       redirect_to @post
     else
       render 'new'
     end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(params[:post].permit(:title, :text, :photo))
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to posts_path
  end
end

private
  def post_params
    params.require(:post).permit(:title, :text, :photo)
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if mobile_device?
      @posts = Post.all.order("created_at DESC")
    else
    @posts = Post.paginate(:page => params[:page], :per_page => 12).order("created_at DESC")
    end
  end
  
   def show
    @post = Post.find(params[:id])
    @url = @post.photo.url(:mobile)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_for @album do |f| %>
  <% if @album.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@album.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @album.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/albums/edit.html.erb
<div id="content">
<h1>Edit Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path, :class => "button" %>
</div>

app/views/albums/index.html.erb
<div id="content">
<div id="home">
<%= link_to 'Home', root_path, :class => "button" %>
</div>
<h1>Albums</h1>
  <% @albums.each do |album| %>
  <div class="album">
    <table>
    <tr>
      <td><h2><%= album.title %></h2></td>
    </tr>
    <tr>
      <% if album.photos.first %>
      <td><%= image_tag album.photos.first.upload.url(:small), :style => "border-radius: 25px;" %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= link_to 'Show', album_path(album), :class => "button" %></td>
      <% if admin_signed_in? %>
      <td><%= link_to 'Edit', edit_album_path(album), :class => "button" %></td>
      <td><%= link_to 'Destroy', album_path(album),
                       method: :delete, data: { confirm: 'Are you sure?' }, :class => "button" %></td>
      <% end %>
    </tr>
    </table>
  </div>
  <% end %>
</div>

app/views/albums/new.html.erb
<div id="content">
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path, :class => "button"%>
</div>

app/views/albums/show.html.erb
<div id="content">
<h1>
  <%= @album.title %>
</h1>
<div id="photos">
<%= render @photos %>
</div>
<% if admin_signed_in? %>
<h2>Add a photo:</h2>
<%= form_for([@album, @album.photos.build], :html => { :multipart => true }) do |f| %>
  <%= f.file_field :upload, multiple: true, name: "photo[upload]", :style => "margin-bottom: 20px;" %>
<% end %>
<% end %>
<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>
<%= link_to 'Back', albums_path, :class => "button", :style => "margin-top: 25px;" %>
<% if admin_signed_in? %>
<%= link_to 'Edit', edit_album_path(@album), :class => "button", :style => "margin-top: 25px;" %>
<% end %>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
<p>
  <strong><%= comment.commenter %></strong>
</p>
 
<p>
  <%= comment.body %>
</p>
</div>

<p>
	
  <% if admin_signed_in? %>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  <% else %>
  <% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "mobile" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Playfair+Display+SC' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Cinzel:700' rel='stylesheet' type='text/css'>
</head>
<body>
<% if admin_signed_in? %>
<%= link_to 'New post', new_post_path %>
<%= link_to 'New Album', new_album_path %>
<%= link_to 'Home', root_path %>
<%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
<% end %>

<% if admin_signed_in? %>
<%= link_to 'Admin Page', posts_path %>
<% else %>
<%= link_to 'Sign In', new_admin_session_path %>
<% end %>


<%= image_tag("banner.png", :alt => "paisley through a lens banner", width: '100%', :style => "border: 3px solid #000;", :class => "rounded") %>

<%= yield %>

</body>
</html>

app/views/photos/_photo.html.erb
<div class="photo">
<a href=<%= photo.upload.url(:mobile) %> class="group" rel="gallery"><%= image_tag photo.upload.url(:small) %></a>
<% if admin_signed_in? %>
<p>
 <%= link_to 'Delete', [photo.album, photo],
               method: :delete,
               data: { confirm: 'Are you sure?' }, :class => "button" %>
</p>
<% end %>
</div>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert("Failed to upload photo: <%= j @photo.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#photos").append("<%= j render(@photo) %>");
<% end %>

app/views/posts/edit.html.erb
<div id="content">
<h1>Editing post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path, :class => "button" %>
</div>

app/views/posts/index.html.erb
 <div id="content">
  <% @posts.each do |post| %>
    <table class="post">
      <tr><td><h1><%= post.title %></h1></td></tr>
      <tr><td><%= image_tag post.photo.url(:small), :class => "rounded" %></td></tr>
      <tr><td class="text"><%= post.text %></td></tr>
      <tr><td><%= link_to 'Show', post, :class => "button" %>
      <%= link_to 'Edit', edit_post_path(post), :class => "button" %>
      <%= link_to 'Delete', post_path(post),
                      method: :delete, data: { confirm: 'Are you sure?' }, :class => "button" %></td></tr>
    </table>
  <% end %>
 </div>

app/views/posts/new.html.erb
<div id="content">
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div id="content">

<h1>
  <%= @post.title %>
</h1>

<%= image_tag @post.photo.url(:large), :class => "rounded" %>
 
<p>
  <%= @post.text %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', posts_path, :class => "button" %>
<%= link_to 'Edit', edit_post_path(@post), :class => "button" %>

</div>

app/views/welcome/index.html.erb
 <div id="content">
  <div id="intro">
  	<%= link_to "Albums", albums_path, :class => "button" %>
  	<h1>Thank you for visting our page!</h1>
  	<p>I created this website so family and friends that are located all over the country can watch Paisley grow up with us.
  		This is only the first version of the site, so we promise more will come. The site is currently being hosted for free,
  		but as we get more and more views, we will need more resources which will cost significant amounts of money. So we ask,
  		only if you can and would like, to please donate to the site so we can continue to keep it running and make it grow. Thank you
  		in advance for any contributions you give.</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="FSLC3QMQWHZ94">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
  </div>
  <%= will_paginate @posts %>
  <% @posts.each do |post| %>
    <table class="post">
      <tr><td><h1><%= post.title %></h1></td></tr>
      <tr><td><%= image_tag post.photo.url(:small), :class => "rounded" %></td></tr>
      <tr><td class="text"><%= post.text %></td></tr>
      <tr><td><%= link_to 'View Post', welcome_path(post.id), :class => "button" %></td></tr>
    </table>
  <% end %>
  <%= will_paginate @posts %>
 </div>

app/views/welcome/show.html.erb
<div id="content">


<h1><%= @post.title %></h1>

<a href=<%= @url %> class="fancybox"><%= image_tag @post.photo.url(:large), :class => "rounded" %></a>
 
<p class="text">
  <%= @post.text %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', root_path, :class => "button", :style => "margin-bottom: 15px;" %>
</div>